"""ANTLR listener + deployment orchestrator for SiteLang.

Responsibilities are deliberately split across small pieces:

  * this listener only *extracts* the site model from the parse tree;
  * ``validation``     validates it semantically;
  * ``html_generator`` turns it into HTML (code generation);
  * ``deploy_api``     talks to GitHub and Vercel;
  * ``deploy()``       orchestrates those stages.
"""

from SiteLangListener import SiteLangListener

import html_generator
import validation
from deploy_api import GitHubClient, VercelClient


class SiteDeployListener(SiteLangListener):
    def __init__(self, github_token="", vercel_token=""):
        self.github_token = github_token
        self.vercel_token = vercel_token
        # Extracted model.
        self.site_name = ""
        self.site_attrs = {}
        self.pages = {}
        self._current_page = None

    # -- tree extraction (listener callbacks) -----------------------------
    def enterSite(self, ctx):
        self.site_name = ctx.STRING().getText().strip('"')

    def enterSiteAttr(self, ctx):
        key = ctx.IDENTIFIER().getText()
        self.site_attrs[key] = ctx.expr().getText().strip('"')

    def enterPage(self, ctx):
        page_name = ctx.STRING().getText().strip('"')
        self._current_page = page_name
        self.pages.setdefault(page_name, {})

    def exitPage(self, ctx):
        self._current_page = None

    def enterPageAttr(self, ctx):
        if self._current_page is not None:
            key = ctx.IDENTIFIER().getText()
            self.pages[self._current_page][key] = ctx.expr().getText().strip('"')

    # -- compiler stages --------------------------------------------------
    def validate(self):
        """Run semantic validation; returns warnings, raises ValidationError."""
        return validation.validate_site(self.site_name, self.site_attrs, self.pages)

    def generate_html(self):
        return html_generator.generate_html(
            self.site_name, self.site_attrs, self.pages
        )

    def deploy(self, dry_run=False, output_path="index.html"):
        """Validate, generate HTML, and (unless dry_run) publish the site.

        Raises validation.ValidationError or deploy_api.DeploymentError on
        predictable failures so the driver can report them cleanly.
        """
        print(f"\n[*] Compiling site definition '{self.site_name}'...")

        warnings = self.validate()
        for warning in warnings:
            print(f"[!] Warning: {warning}")

        html = self.generate_html()

        if dry_run:
            with open(output_path, "w", encoding="utf-8") as fh:
                fh.write(html)
            print(f"[+] HTML generated locally: {output_path} "
                  f"({len(html)} bytes)")
            print("[i] Dry run: skipping GitHub and Vercel (no tokens used).")
            return None

        repo_name = validation.normalize_repo_name(self.site_name)
        description = self.site_attrs.get(
            "description", "Generated by a custom DSL compiler"
        )

        github = GitHubClient(self.github_token)
        full_name, repo_url = github.create_repo(repo_name, description)
        print(f"[+] GitHub repo ready: {repo_url}")

        github.put_file(full_name, "index.html", html,
                        "Initial commit from SiteLang compiler")
        print("[+] index.html pushed to GitHub")

        vercel = VercelClient(self.vercel_token)
        live_url = vercel.deploy(repo_name, html)
        print(f"[✓] Deployed to Vercel: {live_url}")

        print("\n[✓] Done! Your compiler just deployed a live website.")
        return live_url
